CREATE TABLE Users(
    Id UUID NOT NULL PRIMARY KEY,
    Email VARCHAR(70) NOT NULL UNIQUE,
    Password VARCHAR(50) NOT NULL,
    TaxNumber VARCHAR(15) NOT NULL UNIQUE,
    FullName VARCHAR(70) NOT NULL,
    Type VARCHAR(30) NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);