CREATE TABLE TransactionPin(
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    Pin VARCHAR(50) NOT NULL,
    Attempt INT NOT NULL,
    Blocked Bool NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);