CREATE TABLE Wallets(
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    Balance DECIMAL(10, 2) NOT NULL,
    UserId UUID NOT NULL UNIQUE,
    TransactionPinId BIGINT NOT NULL UNIQUE,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (UserId) REFERENCES Users(Id),
    FOREIGN KEY (TransactionPinId) REFERENCES TransactionPin(Id)
);