CREATE TABLE TransactionsPin (
    Id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    Pin VARCHAR(50) NOT NULL,
    Attempt INT NOT NULL,
    Blocked BOOLEAN NOT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdateAt TIMESTAMP
);
