CREATE TABLE Transactions (
    Id BIGSERIAL PRIMARY KEY,
    FromWallet BIGINT NOT NULL,
    ToWallet BIGINT NOT NULL,
    TransactionValue DECIMAL(10, 2) NOT NULL,
    Status VARCHAR(30) NOT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdateAt TIMESTAMP,

    FOREIGN KEY (FromWallet) REFERENCES Wallets(Id),
    FOREIGN KEY (ToWallet) REFERENCES Wallets(Id)
);
